import java.math.BigInteger;
import java.util.*;

class p029 {
    /*
        Consider all integer combinations of a^b for 2 <= a <= 5 and 2 <= b <= 5.
        If placed in numerical order, the sequence of 15 distinct terms is:

        4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

        How many distinct terms are in the sequence generated by a^b for 
        2 <= a <= 100 and 2 <= b <= 100?

        Do as the question says. To keep track of the all the distinct numbers
        generated from going through every combination of a, b, use a set.
    */
    public static int totalDistinctTerms(int aMax, int bMax) {
        Set<BigInteger> allTerms = new HashSet<>();
        for (int a = 2; a <= aMax; a++) {
            for (int b = 2; b <= bMax; b++) {
                allTerms.add(BigInteger.valueOf(a).pow(b));
            }
        }
        return allTerms.size();
    }

    public static void main(String[] args) {
        System.out.println(totalDistinctTerms(100, 100));
    }
}